travis:
  secure:
    BINSTAR_TOKEN: Y1XykYjrygv0ksCrQigEOoVc4ZkJUue31UlhJ85tfdWz2uCzZ5cZUz5d+lYL4nuiy+tsaLGKir6BBIG0RaF+p6rnPfp4GblDuf8bk2eu1+cIp6Tygss9xlZE1be+ABsbn/mJU3c8+ji3YBUkR9tvUX64shFPExt/tS8G1Udn/aQZyAfJWDR4AiqmaNNcjiwZzC1fb8CBB78ORnUN6DumpBXkRLcqLW4o7JEWXEV2BiGZLkjxGvQF3YvPF07C2nn978E9TmdoDYA4pS4jsfqyOCRcrjkFPS2Kn1jrKz4J7i5HHBxrkSRw2AS0lOoMqjactSc6WnKvAyDGZTd85s4bYetVR10YJgjt6iEPHlL7kJratNSVbj2VWBJ+PUTrQfts/j4cCPOP9oQWpb5d8tjkGbsQJM5N0SAZhXg3UxUj4+ZPTV5Q+hHBPkVxe6q9UufZrtafUPRf8c5KUGA2gItG6Ci28CjhjcXFnvHXLLWlGH/mX2B7lAhPzWmIR5uPDt9FJ93zLS9OTvr2alOokt7Vy41NEVUCngN6FRKBmubR36FNrDGPi0Tp/KEgkdfh3EYBm0hsI5kBNcwvxorcs0cnlI5+qP3FuhEFDqdFDyilysTjb+Qchnr05uNvuf5eM07pO2w/IzGuE/m2w67K9LAd38BpjMRX+bVRD38/G2B6cbw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
